/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package runawayrobot;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author phixuanhoan
 */
public class mainForm extends javax.swing.JFrame {
    private int level;
    private int n;
    private int kichThuocToiThieu = 4;
    private int soLuongLevel = 3;
    private JButton[][] Map;
    private int soLuongNuocDi;
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(800, 800);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTaomap = new javax.swing.JLabel();
        txtLevel = new javax.swing.JTextField();
        btnTaoMap = new javax.swing.JButton();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Runaway Robot");
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(252, 229, 231));

        lblTaomap.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lblTaomap.setText("Nhập vào level");

        btnTaoMap.setBackground(new java.awt.Color(255, 255, 255));
        btnTaoMap.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        btnTaoMap.setText("Tạo Map");
        btnTaoMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoMapActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(252, 229, 231));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(411, Short.MAX_VALUE)
                .addComponent(lblTaomap, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTaoMap)
                .addGap(33, 33, 33))
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaomap)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaoMap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int dem = 1;
    private void btnTaoMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoMapActionPerformed
       
        try {
            //Lấy dữ liệu từ textBox
            level = Integer.parseInt(txtLevel.getText());
            n = (level - 1)/soLuongLevel + kichThuocToiThieu;

            panel.removeAll();
            this.setSize(801, 801);
            Map = new JButton[n][n];
            int kichThuoc = 600;
            for(int i = 0; i < n; i++){
                for(int j = 0; j < n; j++){
                    Map[i][j] = new JButton();
                    Map[i][j].setName("map");
                    Map[i][j].setSize(kichThuoc/n, kichThuoc/n);
                    Map[i][j].setLocation(j*Map[i][j].getWidth(), i*Map[i][j].getHeight() + 100);
                    Map[i][j].setFocusPainted(false);
                    Map[i][j].setBorder(new LineBorder(Color.BLACK));
                    //Kiểm tra có phải button ở đích đến hay không(dòng cuối, cột cuối)
                    if( i == n -1 || j == n - 1){
                        Map[i][j].setBackground(Color.BLUE);
                    }
                    panel.add(Map[i][j]);
                    this.setSize(800, 800);
                }
            }
            //Hiển thị Robot lên Map
            ImageIcon imageRobot = new ImageIcon("images/robot.png");
            Image imgRB = imageRobot.getImage();
            Image newImgRB = imgRB.getScaledInstance(Map[0][0].getWidth(), Map[0][0].getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imageRB = new ImageIcon(newImgRB);
            Map[0][0].setIcon(imageRB);
            
            //Hiển trị chướng ngại vật
            //Bước 2: tính số lượng 
            Random rand = new Random();
            int min = (int)((n*n - 2 *n)*(0.15));
            int max = (int)((n*n - 2 *n)*(0.2) + 1);
            int  SoLuongBom = rand.nextInt(max - min) + min; 
//            JOptionPane.showMessageDialog(null, SoLuongBom);
            //Bước 2: cho bom hiển thị theo đúng quy tắc
            for(int  i = 0; i < SoLuongBom; i++){
                int viTriDong_ChuongNgaiVat;
                int viTriCot_ChuongNgaivat;
                do {                    
                    viTriCot_ChuongNgaivat = rand.nextInt(n-1);
                    viTriDong_ChuongNgaiVat = rand.nextInt(n-1);
                } while (Map[viTriDong_ChuongNgaiVat][viTriCot_ChuongNgaivat].getIcon() != null); // Bom khác vị trí Robot
//                JOptionPane.showMessageDialog(null,SoLuongBom +  "--Dong: " + viTriDong_ChuongNgaiVat+ "Cột: " +viTriCot_ChuongNgaivat);
                //Bom không được trùng lên nhau
                /**
                 * Có 2 cách xử lý: Tạo ra 1 mảng lưu trữ thông tin câu hỏi hợp lệ: mỗi câu khi rand ra lại kiểm tra với mảng
                 * xe  có bị trùng không nêos có thì rand 
                 * Cách 2: Mỗi lần random ra xem chỗ đó có Bom chưa
                 */
               
                ImageIcon imageIconBOM = new ImageIcon("images/boom.png");
                Image imgBOM = imageIconBOM.getImage();
                Image newImgBOM = imgBOM.getScaledInstance(Map[0][0].getWidth(), Map[0][0].getHeight(), Image.SCALE_SMOOTH);
                ImageIcon imageBOM = new ImageIcon(newImgBOM);
                Map[viTriDong_ChuongNgaiVat][viTriCot_ChuongNgaivat].setIcon(imageBOM);
                
                
            }
            //Hiển thij nước đi cho phép
            //Bước 1: tính tổng số nước đi dựa trên n
            int maxNuocDi = (int)(0.75 * n) + 1;
            int minNuocDi = (int)(0.5 * n);
            soLuongNuocDi = rand.nextInt(maxNuocDi - minNuocDi) + minNuocDi;
//            JOptionPane.showMessageDialog(null, soLuongNuocDi);
            //Bước 2: button nước đi
            JButton[] DanhSachNuocDi = new JButton[soLuongNuocDi];
            for(int i = 0; i <soLuongNuocDi; i++){
                DanhSachNuocDi[i] = new JButton();
                DanhSachNuocDi[i].setSize(30,30);
                DanhSachNuocDi[i].setLocation(i*DanhSachNuocDi[i].getWidth(), Map[0][0].getLocation().y - DanhSachNuocDi[i].getHeight() - 5);
                this.setSize(801, 801);
                panel.add(DanhSachNuocDi[i]);
            }
            
            
        } catch (Exception e) {
            txtLevel.setText("");
            JOptionPane.showMessageDialog(null, "Dữ liệu phải ở dạng số");
        }
    }//GEN-LAST:event_btnTaoMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoMap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTaomap;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtLevel;
    // End of variables declaration//GEN-END:variables
}
